### ISSUE TITLE
add a rust-toolchain.toml to pin the rust version?

### ISSUE THREAD

**Issue by asukaminato0721** [fish-shell/fish-shell#10256]
I've checked the issues, no relevant issues.

I noticed that

https://github.com/fish-shell/fish-shell/blob/f7b57065dbb06ac9d9a19e696fe039f111758163/.github/workflows/rust_checks.yml#L32-L34

so manually pin a version will fix that. (But require manually bump the toolchain version, which is not so frequently).

something like

```toml
[toolchain]
# older versions may fail to compile; newer versions may fail the clippy tests
channel = "1.75"
components = ["rustfmt", "clippy"]
```

ref https://rust-lang.github.io/rustup/overrides.html
