### ISSUE TITLE
Old history appears "deleted" (~/.local/share/fish/fish_history is ok)

### ISSUE THREAD

**Issue by rciorba** [fish-shell/fish-shell#5136]
Hi!

After restarting my window-manager (awesomewm) and logging in again, I noticed completion was not suggesting commands from history. Running the history command it looked like all history before the WM restart was gone. Fortunately the content of `~/.local/share/fish/fish_history` is ok, all my old history is there, all the new commands are being added correctly, but history and fish completion don't "see" it.

Is this a bug?
How can I get my completion back? (I have already tried rebooting the whole system)

Snippet from ~/.local/share/fish/fish_history 
```
- cmd: curl  'http://127.0.0.1:9201/t-clus-*/_search?ignore_unavailable=true&pretty=true'
  when: 1533390322
- cmd: ~/.venvs/supervisord/bin/supervisord -c ~/repos/misc/supervisor.conf 
  when: 1533540475
- cmd: ps auxf  # first command according as output by history
  when: 1533540548
- cmd: history 
  when: 1533540589
- cmd: ls
  when: 1533540597
- cmd: history 
  when: 1533540601
- cmd: cd repos/
  when: 1533540610
  paths:
    - repos/
- cmd: ls
  when: 1533540610
```

Output of history command:
```
ls
cd repos/
history 
ls
history 
ps auxf
```

System information:
```
-> fish --version
fish, version 2.6.0
-> echo $version
2.6.0
-> uname -a
Linux null 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-> echo $TERM
xterm-256color
```
Thanks!
