### ISSUE TITLE
history does not recognize unexpanded paths

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6097]
After executing a command that includes an unexpanded variable, the `fish_history` file does not register that the command included a path.

e.g.

```fish
~> touch ~/.local/share/fish/fish_history
~> history --merge
~> nvim ~/.local/share/fish/fish_history
```

returns 

```
- cmd: touch ~/.local/share/fish/fish_history
  when: 1568081310
- cmd: history --merge
  when: 1568081342
- cmd: nvim ~/.local/share/fish/fish_history
  when: 1568081344
```

whereas

```fish
~> nvim /home/mqudsi/.local/share/fish/fish_history
```
returns

```
- cmd: nvim /home/mqudsi/.local/share/fish/fish_history
  when: 1568081575
  paths:
    - /home/mqudsi/.local/share/fish/fish_history
```

Even if we don't want to include "regular" variables like `$HOME` or $dir (why not, though?), `~` should probably be locally recognized and expanded by the history handler.
