### ISSUE TITLE
empty cmd in history file breaks history

### ISSUE THREAD

**Issue by JeanMertz** [fish-shell/fish-shell#6494]
I searched for any issue describing this problem, as I can hardly believe I'm the first to run into this, but I couldn't find any, so here it is, feel free to close if this is a duplicate.

```
fish --version
fish, version 3.0.2

uname -rs
Darwin 19.2.0

echo $TERM
xterm-kitty
```

---

I somehow broke my Fish history by getting an entry in there without an actual command.

Basically, my history file looks like this:

```yaml
# many more older entries here...
- cmd: ffmpeg -an -i input.mov -c:v libx264 -preset slow -crf 22  output6.mp4
  when: 1578838355
  paths:
    - input.mov
- cmd: 
  when: 1578838397
- cmd: less Brewfile
  when: 1578838426
  paths:
    - Brewfile
# ~25 newer entries here...
```

When using the up arrow (or starting to type something and using auto-completion), my history search goes back until the `less Brewfile` but nothing older than that.

Using `history` shows me all history in the history file, but it shows a blank line for the empty `cmd` one at 1578838397. Using FZF also works (since I guess it parses the history file itself).

As soon as I delete the history entry with the empty `cmd`, the regular history functionality starts working again (after starting a new shell).

For completeness sake, there's an empty space after the `cmd:`. I can't remember anymore what I actually typed in my shell when that history entry was inserted since it took me a while to figure out what was going on.
