### ISSUE TITLE
Fish history file path detection is broken for path prefixed with `~`

### ISSUE THREAD

**Issue by Blizarre** [fish-shell/fish-shell#7582]
Version: 3.1.0
OS: Ubuntu focal
Terminal: st

Thank you for this project, I have been using fish for years and I love it. I looked at the issues but could not find one like this.

## How to reproduce

When I looked at my `~/.local/share/fish/fish_history` file, I found that files starting with `~`  weren't detected properly as paths:

```
$ md5sum fish.spec.in ~/test.sh /tmp/fish.desktop
5edd6151e8eee9c252fe08e77775d993  fish.spec.in
48a61d611ce2b7bce16a49119909e625  /home/simon/test.sh
4a104f9e1d24ad65fb4aca68aa4d96b8  /tmp/fish.desktop
$ tail -n 7 ~/.local/share/fish/fish_history
- cmd: md5sum fish.spec.in ~/test.sh /tmp/fish.desktop
  when: 1609108437
  paths:
    - fish.spec.in
    - /tmp/fish.desktop
- cmd: tail -n 7 ~/.local/share/fish/fish_history
  when: 1609108439

``` 

## Expectations

```
- cmd: md5sum fish.spec.in ~/test.sh /tmp/fish.desktop
  when: 1609108437
  paths:
    - fish.spec.in
    - ~/test.sh
    - /tmp/fish.desktop
- cmd: tail -n 7 ~/.local/share/fish/fish_history
  when: 1609108439
  paths:
    - ~/.local/share/fish/fish_history
```

## Comments

I do not know if it is really an issue or not, but it explain a few questions that I had in the past where I noticed that the autocomplete was inconsistent, and couldn't really understand why.
