### ISSUE TITLE
Multiline prompt adds new line every time I go in and out of vi normal mode

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#7806]
fish --version: fish, version 3.2.0
OS: macOS 10.15.7
$TERM: alacritty

Every time I go in and out of vi normal mode a newline is added. This is probably due to my starship prompt adding a new line before each prompt (for vertical spacing reasons). I don't think this happened before upgrading to version 3.2.0.

Here's a video of it

https://user-images.githubusercontent.com/59321248/110530737-14eb5800-811b-11eb-8271-458284c0813e.mov

and here's my starship config:

```toml
# ~/.config/starship.toml
[character]
error_symbol = "[λ](fg:red)"
success_symbol = "[λ](fg:purple)"
vicmd_symbol = "[λ](fg:purple)"

[directory]
fish_style_pwd_dir_length = 1
format = " in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1

[hostname]
format = " on [$hostname]($style)"
ssh_only = false

[python]
python_binary = "python3"

[username]
format = "[$user]($style)"
show_always = true
```

Is there a way to fix this?

**Comment by faho** [comment]
What does `type fish_mode_prompt` say?

**Comment by faho** [comment]
Ah, okay, starship already disables that.

Sorry, I can't reproduce this with just your starship configuration. It's likely there's something else that's necessary to cause the problem.

E.g. what's your `locale`? That could cause some width calculations to be off.

**Comment by noib3** [comment]
The only way I can stop having this issue while using starship is with
```toml
add_newline = false

[line_break]
disabled = true
```
if I remove any of those two I experience what I showed above. My locale is
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
I'm not sure why it works on your machine.
