### ISSUE TITLE
fish_history file often getting corrupted

### ISSUE THREAD

**Issue by rapenne-s** [fish-shell/fish-shell#8259]
Hello

I regularly have issues in my fish_history that would contain invalid character and the history would stop working because the file is corrupted. Interestingly, the corruption only appear in kakoune editor and not vim, emacs or ed which would display the file fine. I only need to delete the entry with the corruption to repair my history.

I can reproduce it very easily by spawning 2 xterm, typing a command in both and send a kill signal (not a -9 one) to close both xterm (and writing history). However, it happens regularly in a single terminal using fish.

- fish --version = fish, version 3.3.1
- echo $verison = 3.3.1
- uname -a = OpenBSD daru.lan 7.0 GENERIC.MP#195 amd64
- TERM = xterm-256color
- `sh -c 'env HOME=$(mktemp -d) fish'` I can't really use it because I need to manipulate the history. I don't have plugins installed and the only local config are aliases defined.

ascii recording using a fresh history file https://asciinema.org/a/j7Rx2wKsWgS6GuWwFJYOaMm4h I think it's the best explanation for the issue...

Some bit of my fish_history file that is broken, full of 00 bytes.
```
solene@daru ~> grep -A1000 1630246703 .local/share/fish/fish_history | hexdump -C
00000000  20 20 77 68 65 6e 3a 20  31 36 33 30 32 34 36 37  |  when: 16302467|
00000010  30 33 0a 20 20 70 61 74  68 73 3a 0a 20 20 20 20  |03.  paths:.    |
00000020  2d 20 2e 6c 6f 63 61 6c  2f 73 68 61 72 65 2f 66  |- .local/share/f|
00000030  69 73 68 2f 66 69 73 68  5f 68 69 73 74 6f 72 79  |ish/fish_history|
00000040  0a 2d 20 63 6d 64 3a 20  67 72 65 70 20 2d 41 31  |.- cmd: grep -A1|
00000050  30 20 31 36 33 30 32 34  36 37 30 33 20 2e 6c 6f  |0 1630246703 .lo|
00000060  63 61 6c 2f 73 68 61 72  65 2f 66 69 73 68 2f 66  |cal/share/fish/f|
00000070  69 73 68 5f 68 69 73 74  6f 72 79 0a 20 20 77 68  |ish_history.  wh|
00000080  65 6e 3a 20 31 36 33 30  32 34 36 38 37 36 0a 20  |en: 1630246876. |
00000090  20 70 61 74 68 73 3a 0a  20 20 20 20 2d 20 2e 6c  | paths:.    - .l|
000000a0  6f 63 61 6c 2f 73 68 61  72 65 2f 66 69 73 68 2f  |ocal/share/fish/|
000000b0  66 69 73 68 5f 68 69 73  74 6f 72 79 0a 00 00 00  |fish_history....|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000002a0  00 00 00 00 00 00 00 0a                           |........|
000002a8
```

this is how it looks in editor kakoune when I'm trying to edit
```
 cmd: grep -A10 1630246703 .local/share/fish/fish_history
  when: 1630246876
  paths:
    - .local/share/fish/fish_history
�����������������������������������������������������������������������������������������������������������������������������������������������������������������������
```
