### ISSUE TITLE
history doesn't print anything - but history | grep does (?!)

### ISSUE THREAD

**Issue by androidfred** [fish-shell/fish-shell#8262]
```
$ fish --version 
fish, version 3.3.1)

$ echo $version 
3.3.1

$ uname -a` 
Darwin foomachine 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color

$ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

(ie no plugins)

TLDR
History doesn’t print anything - but history | grep does (?!)

STEPS TO REPRODUCE

```
foouser@foomachine ~/.l/s/fish> pwd
/Users/foouser/.local/share/fish

foouser@foomachine ~/.l/s/fish> cat fish_history 
- cmd: echo FOO
  when: 1630463688
- cmd: history
  when: 1630463691
- cmd: history | grep echo
  when: 1630463694
- cmd: echo $XDG_DATA_HOME
  when: 1630463720
- cmd: cd .local/share/fish/
  when: 1630463731
  paths:
    - .local/share/fish/
- cmd: ls
  when: 1630463731
- cmd: less fish_history
  when: 1630463735
  paths:
    - fish_history
- cmd: history
  when: 1630463745
- cmd: pwd
  when: 1630463799
- cmd: less fish_history
  when: 1630463806
  paths:
    - fish_history
- cmd: pwd
  when: 1630463811
- cmd: cat fish_history
  when: 1630463813
  paths:
    - fish_history
```

^^^ as you can see, there is history in the file

```
foouser@foomachine ~/.l/s/fish> history
foouser@foomachine ~/.l/s/fish> history | grep echo
echo $XDG_DATA_HOME
echo FOO
```

^^^but, bizarrely, history prints nothing, but history | grep does

I’ve done history delete just to make sure there are no corrupted characters or anything, but the issue persists
