### ISSUE TITLE
Fish history should save the directory (or directories) under which the command was run.

### ISSUE THREAD

**Issue by KamilBaczkowski** [fish-shell/fish-shell#8424]
As in the title, when executing a command, the current directory should be saved as an entry in the history file. That way, fish could give better recommendations to commands, and you would introduce a new way of filtering history, which would be very useful.
Currently the structure looks like that:
```yaml
- cmd: cat some/file/path
  when: 1636402372
  paths:
    - some/file/path
```
A new property like `working_dirs` would store where the command was actually run
```yaml
- cmd: cat some/file/path
  when: 1636402372
  paths:
    - some/file/path
  working_dirs:
    - /one/working/dir
    - /another/one
```
